name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    # - name: Build
    #   run: cargo build
    # - name: Clippy
    #   run: cargo clippy
    - name: Run tests
      env: 
        MAP_SERVER_BIN_PATH: "../target/debug/map-server"
        RUST_LOG: "WARN"
      run: cargo test --features map_server_inside
    - name: Release
      run: cargo build --release
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push map-server Docker image
      uses: docker/build-push-action@v3
      with:
        context: "./map-server"
        push: true
        tags: dlhxzb/map-server:latest

    - name: Build and push game-server Docker image
      uses: docker/build-push-action@v3
      with:
        context: "./game-server"
        push: true
        tags: dlhxzb/game-server:latest
